Skip NetworkStatsBinderTest if the binder interface is not accessible.
Following up from aosp/3313055, the binder interface getUidStats(II)J
is removed from the module. Currently, the test catches
NoSuchMethodException for reflection.
But did not properly skip for NoSuchMethodError which is thrown by
the java runtime when a method was present during compilation is
no longer available.

Test: cts-tradefed run commandAndExit cts -m CtsNetTestCases -t \
     android.net.cts.NetworkStatsBinderTestinderTest
Bug: 378982661
Merged-In: I7b8baa7ab98ce0114541bf1a9568db6f832213b6
Change-Id: I7b8baa7ab98ce0114541bf1a9568db6f832213b6
(cherry picked from commit 2eff85b7610ac1160ee6ea42cbac4767e6de4ef7)